name: Deploy AWS Lambda Function
# Trigger workflow on push to main or pull request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
       
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    # Add permissions needed for OIDC authentication with AWS
    permissions:
      id-token: write
      contents: read
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Checkout private action
        uses: actions/checkout@v3
        with:
          repository: chloe1818/lambda-github-action
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
          path: .github/actions/lambda-github-action
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::660753258521:role/GitHubActionsDeployRole
          aws-region: us-west-2
    
      - name: Deploy Lambda
        uses: chloe1818/lambda-github-action@v1
        with:
          function-name: test-lambda
          code-artifacts-dir: ./dist 
          memory-size: 256
          publish: true
