name: Deploy AWS Lambda Function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
       
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::660753258521:role/GitHubActionsDeployRole
          aws-region: us-west-2
    
      - name: Deploy Lambda
        uses: chloe1818/lambda-github-action@main
        with:
          function-name: test-lambda
          zip-file-path: ./lambda-function.zip
          memory-size: 256
          publish: true